POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjNkMDBhMDMwMzEwOTQxMTYwNjFjZWNhIiwiaWF0IjoxNjc0NTc4NDk0LCJleHAiOjE2NzQ1ODIwOTR9.Iygh0musXs-wSw62r46BspCWqHu0YGmooApDM8zTf64

{
    "title": "Objects",
    "author": "Michael Chan",
    "url": "wwww.michaelchanwebsite.com",
    "likes": 0,
    "userId": "60bd0a36a46a861cf4719f8f"
}